source 'https://rubygems.org'
ruby '2.6.3'

gem 'rails', '5.1'
gem 'pg', '~> 0.20'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'
gem 'devise_token_auth', '1.1.0'
gem 'erubis'
gem 'bootstrap-sass'
gem 'aws-sdk-v1'
gem 'aws-sdk'
gem 'paperclip'
gem 'bower-rails', '~> 0.11.0'
gem 'angular-rails-templates'
gem 'acts_as_commentable_with_threading'
gem 'fog-aws'
gem 'carrierwave'
gem 'carrierwave_direct'
gem 'populator'
gem 'faker'
gem 'paperclip-av-transcoder'
gem 'foreman'
gem 'rollbar'
gem 'puma'
gem 'rack-timeout'
gem 'zencoder'
gem 'user_impersonate2', require: 'user_impersonate'
gem 'browser'
gem 'socialization'
gem 'sucker_punch', '~>2.0.0'
gem 'role_model'
gem 'stripe'
gem 'aws-flow', '~>3.0.0'
gem 'omniauth-facebook'
gem 'kaminari'
gem 'font-awesome-rails'
gem 'rack-rewrite', '~> 1.5.0'
gem 'rails-i18n', '~> 5.1.3'
gem 'geocoder'
gem 'i18n_data'
gem 'pusher'
gem 'paranoia', '~> 2.2'
gem 'sendgrid-ruby'
gem 'omniauth', github: 'ryaz/omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-slack', github: 'ryaz/omniauth-slack'
gem 'http'
gem 'validates_email_format_of'
gem 'xmlrpc'
gem 'aws-sdk-s3'

group :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm'
end

group :development do
  gem 'spring', '~> 1.3.6'
  gem 'letter_opener'
  gem 'bullet'
  gem 'zencoder-fetcher'
  gem 'httplog'
end

group :development, :test do
  gem 'capybara'
  gem 'capybara-angular'
  gem 'capybara-screenshot', '~> 1.0.13'
  gem "factory_bot_rails"
  gem 'ffaker'
  gem 'rspec-rails', '~> 3.0'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'shoulda-matchers', '~> 2.8.0'
  gem 'jasmine', github: 'pivotal/jasmine-gem'
  gem 'rubocop'
  gem 'minitest-ci', github: 'circleci/minitest-ci'
  gem 'timecop'
  gem 'rails-erd'
end

group :test do
  gem 'poltergeist'
  gem 'selenium-webdriver', '~> 3.4.0'
  gem 'chromedriver-helper', '~> 1.1.0'
  gem 'site_prism'
  gem 'simplecov', require: false
  gem 'database_cleaner'
  gem 'sqlite3'
  gem 'rspec_junit_formatter'
  gem 'rspec-json_expectations'
end
